---
name: Continous integration of Salt LSP

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    name: run tests for python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}

      - name: install dependencies
        run: poetry install

      - name: run the tests
        run: poetry run pytest

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
          flags: "unittests,python-${{ matrix.python-version }}"

      - name: generate the cached completion data and try to launch the server
        run: |
          poetry run ./create_completion_classes.py
          poetry run ./lsp_server.py --stop-after-init

  lint:
    name: lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}

      - name: install dependencies
        run: poetry install

      - name: run black
        run: poetry run black --check --diff salt_lsp/*py tests/*py

      - name: run mypy
        run: poetry run mypy salt_lsp/*py

      - name: run pylint
        run: poetry run pylint --fail-under 9.2 salt_lsp/*py
